In [26]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score,
    roc_auc_score,
    classification_report,
    confusion_matrix,
    roc_curve,
    precision_recall_curve
)
import matplotlib.pyplot as plt


data = "/Users/katakitaeva/Desktop/DPO/Grib/homeworks/HW05/S05-hw-dataset.csv" 
df = pd.read_csv(data)

In [11]:
display(df.head())

client_id  age  income  years_employed  credit_score  debt_to_income  \
0          1   25   94074              22           839        0.547339   
1          2   58   51884              26           565        0.290882   
2          3   53   48656              39           561        0.522340   
3          4   42   81492              30           582        0.709123   
4          5   42   94713               8           642        0.793392   

   num_credit_cards  num_late_payments  has_mortgage  has_car_loan  \
0                 1                  7             0             0   
1                 1                  1             0             1   
2                 1                 13             0             0   
3                 2                 10             1             1   
4                 3                  3             0             0   

   savings_balance  checking_balance  region_risk_score  \
0            26057              5229           0.080052   
1            16221             11595           0.428311   
2            55448             -2947           0.770883   
3            35188             17727           0.357619   
4                0              -404           0.414260   

   phone_calls_to_support_last_3m  active_loans  customer_tenure_years  \
0                              19             1                      8   
1                              15             0                      7   
2                              15             4                      5   
3                               0             2                      7   
4                              17             1                     10   

   default  
0        0  
1        0  
2        0  
3        1  
4        1

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   client_id                       3000 non-null   int64  
 1   age                             3000 non-null   int64  
 2   income                          3000 non-null   int64  
 3   years_employed                  3000 non-null   int64  
 4   credit_score                    3000 non-null   int64  
 5   debt_to_income                  3000 non-null   float64
 6   num_credit_cards                3000 non-null   int64  
 7   num_late_payments               3000 non-null   int64  
 8   has_mortgage                    3000 non-null   int64  
 9   has_car_loan                    3000 non-null   int64  
 10  savings_balance                 3000 non-null   int64  
 11  checking_balance                3000 non-null   int64  
 12  region_risk_score               30

In [14]:
df.describe()

client_id          age         income  years_employed  credit_score  \
count  3000.000000  3000.000000    3000.000000     3000.000000   3000.000000   
mean   1500.500000    45.059667   69658.992000       19.577667    649.285333   
std     866.169729    14.192883   24742.235182       11.381497     69.955852   
min       1.000000    21.000000   15000.000000        0.000000    402.000000   
25%     750.750000    33.000000   52641.750000       10.000000    604.000000   
50%    1500.500000    45.000000   69784.500000       20.000000    647.000000   
75%    2250.250000    57.000000   85874.250000       29.000000    697.000000   
max    3000.000000    69.000000  156351.000000       39.000000    850.000000   

       debt_to_income  num_credit_cards  num_late_payments  has_mortgage  \
count     3000.000000       3000.000000        3000.000000   3000.000000   
mean         0.284065          3.494667           6.869333      0.495000   
std          0.161112          2.289917           4.291278      0.500058   
min          0.006147          0.000000           0.000000      0.000000   
25%          0.157796          1.000000           3.000000      0.000000   
50%          0.261726          3.000000           7.000000      0.000000   
75%          0.388886          6.000000          10.000000      1.000000   
max          0.878343          7.000000          14.000000      1.000000   

       has_car_loan  savings_balance  checking_balance  region_risk_score  \
count   3000.000000      3000.000000       3000.000000        3000.000000   
mean       0.501333     20607.256667       5559.684333           0.400175   
std        0.500082     14035.209739       6306.032612           0.204529   
min        0.000000         0.000000      -3000.000000           0.001148   
25%        0.000000      9612.250000        341.500000           0.239208   
50%        1.000000     20021.000000       5114.500000           0.381992   
75%        1.000000     30101.250000       9906.250000           0.549213   
max        1.000000     75237.000000      29335.000000           0.961733   

       phone_calls_to_support_last_3m  active_loans  customer_tenure_years  \
count                     3000.000000   3000.000000            3000.000000   
mean                         9.524667      1.976333               6.968667   
std                          5.779030      1.408700               4.349942   
min                          0.000000      0.000000               0.000000   
25%                          5.000000      1.000000               3.000000   
50%                         10.000000      2.000000               7.000000   
75%                         15.000000      3.000000              11.000000   
max                         19.000000      4.000000              14.000000   

           default  
count  3000.000000  
mean      0.410333  
std       0.491976  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       1.000000  
max       1.000000

In [24]:
# распределение целевого признака default (например, через value_counts(normalize=True)).

print("Распределение (количество и доля):")
counts = df['default'].value_counts()
proportions = df['default'].value_counts(normalize=True)
print("Количество:")
print(counts)
print("\nДоли (проценты):")
print((proportions * 100).round(1).astype(str) + "%")

Распределение (количество и доля):
Количество:
default
0    1769
1    1231
Name: count, dtype: int64

Доли (проценты):
default
0    59.0%
1    41.0%
Name: proportion, dtype: object


In [31]:
#negative_cols = []
print("проверка MIN/MAX:")
for col in numeric_cols[:10]:  # первые 10 колонок
    print(f"{col:20} min={df[col].min():8.2f} max={df[col].max():8.2f}")

проверка MIN/MAX:
client_id            min=    1.00 max= 3000.00
age                  min=   21.00 max=   69.00
income               min=15000.00 max=156351.00
years_employed       min=    0.00 max=   39.00
credit_score         min=  402.00 max=  850.00
debt_to_income       min=    0.01 max=    0.88
num_credit_cards     min=    0.00 max=    7.00
num_late_payments    min=    0.00 max=   14.00
has_mortgage         min=    0.00 max=    1.00
has_car_loan         min=    0.00 max=    1.00


Кратко (несколько предложений) зафиксировать наблюдения:

сколько объектов и признаков в датасете;
есть ли явные аномалии (например, явно невозможные значения);
как распределён таргет (баланс классов).


В таблице 3000 строк и 17 колонок, две из которых содержат значения float64 и пятнадцать - int64.
59.0% значений столбца "default" = 0, 41.0% = 1. Явных аномалий не обнаружено (все максимальные и минимальные значения в рамках адекватного).

In [33]:
# Выделить матрицу признаков X и вектор таргета y:
# таргет – столбец default;
# в качестве признаков использовать все остальные осмысленные столбцы (кроме client_id, который можно удалить или не использовать в X).


y = df['default'].copy()
print(f" Target y: столбец 'default', размер {y.shape}")

columns_to_drop = ['default']
if 'client_id' in df.columns:
    columns_to_drop.append('client_id')

X = df.drop(columns=columns_to_drop).copy()
print(f" Features X: {X.shape[1]} признаков, размер {X.shape}")

 Target y: столбец 'default', размер (3000,)
 Features X: 15 признаков, размер (3000, 15)
